"""
   This is the main file of the framework. The framework is used to measure the
   statistics of the code generated by the LLMs. The framework takes an input
   json file as input. The input json file should contain the mode of the
   framework and the prompts for the LLMs. The framework will then generate
   code using the connected LLMs and measure the statistics of the code.
"""

from modules.input_processor import InputProcessor
from modules.process_code_prompt import ProcessCodePrompt
from modules.check_code_validity import CheckCodeValidity

import argparse
import os

def main(prompts, output_dir):
    # Check if the output directory exists
    if not os.path.exists(output_dir):
        print(f"Directory {output_dir} does not exist")
        return

    process_mode_and_code_prompt_obj = ProcessCodePrompt(prompts)
    outputs = process_mode_and_code_prompt_obj.process_code_prompts(output_dir)

    if outputs == []:
        return

    # When the output of the LLMs is only code that does not need to be checked,
    # the check_code_validity object will can be skipped
    check_code_validity_obj = CheckCodeValidity(outputs)
    outputs = check_code_validity_obj.check_code_validity()


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="LLM Energy Connect")
    parser.add_argument("--input_file", type=str, help="Input json file")
    parser.add_argument("--output_dir", type=str, help="Output directory")
    args = parser.parse_args()

    input_parser_obj = InputProcessor(args.input_file)
    input_parser_obj.process_input()

    prompts = input_parser_obj.get_prompts()

    main(prompts, args.output_dir)